### ISSUE TITLE
?

### ISSUE THREAD

**Issue by WellersonL** [zer0dx/zbxstrike#1]
Traceback (most recent call last):
  File "zbxstrike.py", line 97, in <module>
    main()
  File "zbxstrike.py", line 92, in main
    zbx.attack()
  File "zbxstrike.py", line 54, in attack
    sys.stdout = open('/dev/null', 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/dev/null'

**Comment by zer0dx** [comment]
Hi,
Whats your linux distribuition?
